services:
  chatbot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - .env
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Set environment variable in .env file
    restart: unless-stopped
